### PR TITLE
Update notebooks to 19.12, CFS filesystem

### LINKED ISSUE #31: Problems with 19.9 release
Really only one serious problem, and a few questions.

- [X] `dc17a-truth.ipynb`: No problems.
- [x] `FiberAssign.ipynb`: Command-line `fiberassign` program raised an exception, see below.
- [x] `FiberAssignDECaLS.ipynb`: Probably has similar problems.
- [x] `FiberAssignMocks.ipynb`: Probably has similar problems.
- [X] `Intro_to_DESI_Spectra.ipynb`: No problems.
- [ ] `redshift-database.ipynb`:  Redshift database tutorial does not incorporate 'bright' files: `targets-bright.fits`, `truth-bright.fits`.
- [X] `simulating-desi-spectra.ipynb`:  No problems.
- [X] `survey-simulations.ipynb`: No problems.
- [X] `redrock/RedrockOutputs.ipynb`: No problems.
- [ ] `redrock/RedrockBOSSDemo.ipynb`: Is this relevant?

Other notes:

- desitarget tag 0.33.2 has `desitarget.__version__ = '0.33.2.dev3577'`.
- We are not running on a tagged version of speclite, `speclite.__version__ = '0.9dev514'`.
- The notebook server(s) do not appear to have `$SCRATCH` defined.  Had to switch to `$CSCRATCH`.  Reported this to NERSC Consulting.

Exception reported in `FiberAssign.ipynb`
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/1.2.0/lib/python3.6/site-packages/fiberassign-1.2.0-py3.6-linux-x86_64.egg/fiberassign/assign.py", line 1131, in merge_results_tile
    skymon[field] = outdata[field][sky_rows]
ValueError: no field of name BRICKID
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/1.2.0/bin/fiberassign", line 4, in <module>
    __import__('pkg_resources').run_script('fiberassign==1.2.0', 'fiberassign')
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/1.2.0/lib/python3.6/site-packages/fiberassign-1.2.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/fiberassign", line 168, in <module>
    run_merge(merge_args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/1.2.0/lib/python3.6/site-packages/fiberassign-1.2.0-py3.6-linux-x86_64.egg/fiberassign/scripts/merge.py", line 153, in run_merge
    copy_fba=(not args.skip_raw))
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/1.2.0/lib/python3.6/site-packages/fiberassign-1.2.0-py3.6-linux-x86_64.egg/fiberassign/assign.py", line 1341, in merge_results
    results = pool.map(merge_tile, tile_map_list)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: no field of name BRICKID
```

### LINKED ISSUE #33: Target selection in the FiberAssignMocks notebook
Hi people!

I can not run the target selection command in the FiberAssignMocks notebook on desi 19.2 environment and branch master:

`srun -A desi -N 2 -n 16 -c 8 -C haswell -t 01:00:00 --qos interactive  mpi_select_mock_targets --no-spectra --nproc 4 --nside 32 --seed 10 -c ./input.yaml  --output_dir ./  --tiles ./tiles.fits`

It shows the following error message:

ERROR:mpi_select_mock_targets:176:<module>: Pixels [4509] failed after 7.2 minutes
ERROR:mpi_select_mock_targets:179:<module>: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.28.0/lib/python3.6/site-packages/desitarget-0.28.0-py3.6.egg/EGG-INFO/scripts/mpi_select_mock_targets", line 170, in <module>
    healpixels=rankpix[i:i+n], no_spectra=args.no_spectra)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.28.0/lib/python3.6/site-packages/desitarget-0.28.0-py3.6.egg/desitarget/mock/build.py", line 872, in targets_truth
    MakeMock=AllMakeMock[ii])
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.28.0/lib/python3.6/site-packages/desitarget-0.28.0-py3.6.egg/desitarget/mock/build.py", line 171, in read_mock
    nside_galaxia=nside_galaxia, mock_density=mock_density)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.28.0/lib/python3.6/site-packages/desitarget-0.28.0-py3.6.egg/desitarget/mock/mockmaker.py", line 3204, in read
    only_coords=only_coords, seed=self.seed)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.28.0/lib/python3.6/site-packages/desitarget-0.28.0-py3.6.egg/desitarget/mock/mockmaker.py", line 2104, in readmock
    raise IOError
OSError

I tried to run this notebook in the desi master environment, but there is no the mpi_select_mock_targets function in the master env.

Could anyone please help me?
Thanks a lot!

### LINKED ISSUE #35: update tutorials for project -> cfs directories
Update all tutorials to refer to `/global/cfs/cdirs/desi/` instead of `/global/project/projectdirs/desi/` or `/project/projectdirs/desi/` .

### LINKED ISSUE #38: Notebooks require data that has been removed from NERSC
The notebooks dc17a-truth.ipynb and redrock/RedrockOutputs.ipynb use `desi/datachallenge/dc17a-twopct/` which was recently removed from NERSC spinning disk.  Do we restore the data set, deprecate these notebooks or update them to use a different, *circa* 2020 data set?

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

* Closes #36 
* Fixes #38 
* Fixes #35 
* Fixes #33 (not explicitly, but there are no problems with that notebook)
* Fixes #31

Still need to work on these notebooks:

- [x] redshift-database (yet another data model update needed)
- [ ] dc17a-truth (use newer data set as recommended in #38)
- [x] redrock/RedrockOutputs (use newer data set as recommended in #38)

Other active notebooks have already been tested on 19.12, or on master, for the fiberassign notebooks.  Do we want to move to running the fiberassign notebooks on an explicit release?

### CODE REVIEW

**Comment by weaverba137** [comment]
To save time, I'm declaring the redshift database tutorial done, since it works fine when *only* program='dark' is loaded.  Loading both bright and dark will be moved to a separate issue on desispec.

**Comment by weaverba137** [comment]
@sbailey, please take a look at this block of text from dc17a-truth.  What would be the equivalent file(s) and text for reference run 19.12?

The actual true input spectra were not included with dc17a, but they are available at
NERSC in:
```
/project/projectdirs/desi/datachallenge/dc17a-twopct/targets/{group}/truth-{brickname}.fits
```
where `group = brickname[0:3]`, i.e. the first 3 characters of the brickname.

**NOTE**: future data challenges will group the input truth files by healpix like the output spectra, but dc17a did not.

The above target came from brickname 0084m085.  If you are running locally (not at NERSC), go get that file now, e.g.
```
mkdir -p targets/008/
scp edison.nersc.gov:/scratch2/scratchdirs/sjbailey/desi/dc17a/targets/008/truth-0084m085.fits targets/008/
```
Let's see what is in that file:

**Comment by weaverba137** [comment]
@sbailey , can you take a look at this please?

**Comment by sbailey** [comment]
Thanks.  Let's merge this as-is, and I'll spin the dc17a-truth question into a new ticket to solve independently of the other progress in this PR.

**Comment by weaverba137** [comment]
@sbailey, please do not create a tag!  I want to put a warning into two notebooks that they are still broken.  I was hoping you would address the question but not close the PR.  Note that the WIP tag was still in effect!

In addition to dc17a-truth being broken, #32 is still broken.

**Comment by sbailey** [comment]
For the remaining problems with tutorials on 19.12, please open one ticket per problem to avoid the omnibus ticket effect of some things being solve but not others.

I moved the dc17a-truth question into ticket #40 .

Ideally the fiberassign notebooks would refer to 19.12, but ok to leave them on master for this iteration too if that is needed.

I won't make a tag.  Thanks.

**Pull request merged**
