### PR TITLE
Update database notebook

### PR DESCRIPTION
**Pull request by weaverba137**
This PR finalizes the database example notebook using all tagged software and the final database location.

### CODE REVIEW

**Review by forero — APPROVED** [review]
To test the notebook I had to install kernel 23.1. Then I had a problem connecting to the database using pgpass. The problem was easy to solve from the link to the documentation already included in the notebook. Everything went smoothly afterwards. The explanations were clear and the examples relevant. I found this notebook enlightening. It's nice to see how to prepare some plots that otherwise would take a crazy amount of file reading and ID matching.

**Comment by weaverba137** [comment]
@forero, good to know that the documentation was clear enough to solve those problems. Would you make any recommendations about improving that further?

**Comment by forero** [comment]
@weaverba137 Probably my only recommendation would be adding a comment along these lines: "If you find a problem using this notebook, please fill out an new issue on github describing your 
 situation https://github.com/desihub/tutorials/issues/new/choose"

**Comment by weaverba137** [comment]
I added a line about GitHub issues as suggested.

**Pull request merged**
