### PR TITLE
test and update tutorials to use 18.7 software release

### PR DESCRIPTION
**Pull request by moustakas**
This PR tests our tutorials against the 18.7 software release, in preparation for the Barcelona meeting this week.  Most updates were very minor (e.g., changing the text from 18.6 to 18.7.)

The biggest change (which @sbailey is welcome to revert, but see the discussion in #19) is that I moved the GFA tutorial (which didn't work for me out of the box) to the `archive` subdirectory.

### CODE REVIEW

**Comment by weaverba137** [comment]
@moustakas, is it possible for you to run "Restart kernel and clear outputs" on the notebooks and then save them?  That will hopefully make it possible to see what inputs have changed in the difference view.

**Comment by moustakas** [comment]
I could, but I thought there'd be value in having the outputs displayed.  The changes really were minimal, but in any case I'll do as requested.

**Comment by weaverba137** [comment]
Thanks for doing that, but it turns out the master versions don't have the "clear outputs" applied to them, so I'm afraid that didn't really help.  I'm just trying to get people into the habit of doing that, so that we can see meaningful changes when comparing notebooks in PRs.

**Comment by sbailey** [comment]
@moustakas thanks for vetting/updating these tutorials for 18.7.

+1 for archiving the GFA tutorial.  We should revive that tutorial into a working state as documentation somewhere since it will be needed by the commissioning instrument and early commissioning, but I agree that isn't isn't a general purpose broad-audience tutorial.

I think these tutorials are like the mini test, where having the fully populated version in github is useful as documentation.  i.e. let's *not* "Restart kernel and clear outputs" before committing.  I agree that makes comparing differences a pain, but it makes the end product more useful because someone can read the tutorial and see the output without requiring a NERSC account, setting up a jupyter kernel, etc.

**Comment by moustakas** [comment]
So do you want me to rerun them, commit, and merge?

**Comment by sbailey** [comment]
@moustakas yes, thanks.

**Pull request merged**
