### PR TITLE
Tutorials for release 18.9

### PR DESCRIPTION
**Pull request by weaverba137**
This PR is *in preparation* for getting the tutorials working with release 18.9.

**DO NOT MERGE YET!**

Below are comments on individual tutorials.

## dc17a-truth

```
Code versions used for this tutorial:
python      : 3.6.6
numpy       : 1.13.3
scipy       : 1.1.0
astropy     : 2.0.7
yaml        : 3.12
matplotlib  : 2.1.2
desiutil    : 1.9.13.dev693
desispec    : 0.23.1.dev2840
specter     : 0.9.0.dev536
speclite    : 0.8
```

* Works, but with the caveat that this is dc17a.

## GFA_targets

* Looks like the problems described in the note at the top got fixed, because everything worked.
  - What should we replace this with?  Is the selection still being updated?
* Uses DR4 sweeps.
* Does `get_all_gfa_targets()` really need to be that slow, for a tutorial?
* `get_all_gfa_targets()` does `import numpy as np`, but doesn't actually use it.

## Intro_to_DESI_spectra

* Testing with /global/cscratch1/sd/sjbailey/desi/dev/end2end.
* Lots of `RA_TARGET` --> `TARGET_RA`.
* Hit failure at
  ```
  stds = np.where(specobj.fibermap["DESI_TARGET"] & desi_mask["STD_FSTAR"])[0]
  ```
  - What is the new bit in `desitarget.targetmask.desi_mask`?

## redshift-database

* Works with truth table fix on /global/cscratch1/sd/sjbailey/desi/dev/end2end.
  - Double check on reference run 18.9 when available.
* Questions:
  - The Moon example now only has one exposure with the Moon up.  Is this expected?
  - Nights that have data has also changed.

## simulating-desi-spectra

* `make_templates()` includes a fourth output, `objmeta`.
* `rrdesi` fails with:
```
Running on a batch node:
rrdesi /global/cscratch1/sd/bweaver/desi/simspec/qso-observed-spectra.fits --zbest /global/cscratch1/sd/bweaver/desi/simspec/qso-zbest.fits

srun: job 15438852 queued and waiting for resources
srun: job 15438852 has been allocated resources
Running with 32 processes
Loading targets...
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/redrock/master/py/redrock/external/desi.py", line 588, in rrdesi
    comm=comm, cache_Rcsr=True)
Proc 0:   File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/redrock/master/py/redrock/external/desi.py", line 286, in __init__
    bname = frow["BRICKNAME"]
Proc 0:   File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/row.py", line 46, in __getitem__
    return self._table.columns[item][self._index]
Proc 0:   File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 109, in __getitem__
    return OrderedDict.__getitem__(self, item)
Proc 0: KeyError: 'BRICKNAME'
```

## survey-simulations

* Uses datachallenge/surveysim2017
* Seems to work fine.

## redrock

* Do we need to test the redrock tutorials?

### CODE REVIEW

**Comment by dkirkby** [comment]
Who is the audience for the GFA_targets notebook?  It looks more like (useful) internal documentation than a tutorial on a user-facing API.

**Comment by moustakas** [comment]
> Who is the audience for the GFA_targets notebook? It looks more like (useful) internal documentation than a tutorial on a user-facing API.

I totally agree that we should relegate the GFA_targets notebook.  I'm testing it with the `18.7` software release and having a boatload of issues.  In addition, I think the fact that it uses DR4 suggests it's due for a major rewrite / update (e.g., in that it doesn't use Gaia).

**Comment by weaverba137** [comment]
Would anyone object if I close this PR?  I think we'll just need to start from scratch once the next software release comes out (*e.g.* 18.11).

**Comment by weaverba137** [comment]
Having heard no objections, I'm closing without merging.

**Pull request closed without merging**
