### PR TITLE
EDR Tutorial 

### PR DESCRIPTION
**Pull request by Ragadeepika-Pucha**
This notebook is a modification from the everest tutorial notebook, and also showcases the summary redshift catalogs.

### CODE REVIEW

**Comment by forero** [comment]
Hi @Ragadeepika-Pucha . Thanks for this PR!

I have some suggestions prompted by thinking about this notebook as an on-boarding tool for students and postdocs that are new to DESI. The side effect is that those suggestions could be annoying to more experienced DESI users, so feel free to ignore them!

* In the first mention to EFFTIME_SPEC, please add a link to the most relevant DocDB/wiki page explaining the concept.
* In the first mention to FAFLAVOR, please add a link to the most relevant DocDB/wiki page explaining what is cmx,sv1,sv2,sv3.
* In the line with `sv1_targetmask.desi_mask` it would be nice to have some short narrative around it, i.e. "Although this looks like a very long list of targets, there are only four main target types that we use in DESI: [some link explaning the generalities about BGS, ELG, LRG and QSO]. The long list simply reflects the complexity in the target selection process."
* In the first appearance of long lines of code such as
`is_bgs = (sv1_desi_tgt & sv1_desi_mask['BGS_ANY'] != 0)|(sv2_desi_tgt & sv2_desi_mask['BGS_ANY'] != 0)|(sv3_desi_tgt & sv3_desi_mask['BGS_ANY'] != 0)`, it would be useful to have some short narrative around it, i.e. "For instance, the following line selects all the BGS targets observed in the SV1, SV2 and SV3 campaigns.". 
* In the last part of the notebook it would be useful to have an example on how to overplot the redrock template fit. That's available here https://github.com/desihub/tutorials/blob/main/redrock/RedrockOutputs.ipynb.

Finally, I replaced your matplotlib style lines with a single line `plt.style.use('../mpl/desi.mplstyle')`

Thanks!

**Comment by Ragadeepika-Pucha** [comment]
Hi @forero, 
Thank you very much for the comments! They have been very useful in improving the tutorial notebook. A few points to note:
* I could not find any relevant page regarding EFFTIME_SPEC. Let me know if you have any particular link in mind. 
* I have removed `FAFLAVOR` parts in the notebook, since this is mostly internal to the collaboration and the target selection.
* I did try including the redrock template fit, however the code is exactly repetitive from the link you sent. Thus, I added the link at the end of the notebook for anyone who wish to explore that. I would like to keep the focus on the existing files and accessing the spectra and redshift information in this notebook.

Thank you!
Raga

**Comment by forero** [comment]
Thanks @Ragadeepika-Pucha! Thanks for including some of the additional links. Unfortunately, I don't know what would be the best reference regarding EFFTIME_SPEC, perhaps @julienguy knows? Apart from that, I think this is ready to merge.

**Comment by Ragadeepika-Pucha** [comment]
Thank you @forero. I can create another PR when the public links are available and update the tutorial before the EDR release. Can you please merge this PR or should we ask Stephen Bailey for the same?

**Comment by forero** [comment]
Merged! Thanks @Ragadeepika-Pucha

**Pull request merged**
