### PR TITLE
update tutorials for 19.2 software release

### PR DESCRIPTION
**Pull request by sbailey**
This PR makes minor updates to the tutorials based on testing with the 19.2 branch.  All tutorials work with 19.2 except:
* survey-simulations: still based on old desisurvey/surveysim in 18.11; this PR added comments about needing 18.11 but not supporting 18.12 or 19.2 yet.  See #23
* redshift-database: I didn't get this one working with any recent release so left it as-is; see #22

### CODE REVIEW

**Comment by weaverba137** [comment]
@sbailey, unless you need to merge this quickly, I'll add my database fixes to this branch.

**Comment by sbailey** [comment]
If you can do it today, go ahead, otherwise I'd like to merge this weekend in prep for the workshop next week, even if the redshift-database tutorial comes a bit later.

**Comment by weaverba137** [comment]
1508310 fixes #22, but be sure to (in order):

1. Merge desihub/desispec#770 
2. Update desispec/master on cori
3. Test the redshift tutorial with the DESI master kernel (it should already be set in the notebook).
4. Finally merge this when ready.

**Comment by sbailey** [comment]
Thanks.  Steps tested in that order and everything works as advertised.  Thanks for the updates.  Merging now.

P.S. I especially like the "Fly me to the moon" title.

**Pull request merged**
