### PR TITLE
Database access with a public user

### PR DESCRIPTION
**Pull request by weaverba137**
This PR updates the database notebook to use a database username that would be accessible to the public (with a NERSC account).  It needs some testing before merging.

### CODE REVIEW

**Comment by sbailey** [comment]
The tutorial looks good, but I made two updates:
  * add the pre-installed /global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/specprod-db/main/py to sys.path instead of assuming that the user has a checkout in $HOME/Documents/Code/git/desihub/specprod-db .
  * update the .pgpass instructions to try to connect to the DB and print what to do if it fails, rather than having the actual .pgpass updates as cells.  The previous version of the notebook would have destroyed a user's .pgpass file if they had "run all cells" without carefully reading and understanding the implications.
    * detail: specprodDB.load.setup_db returns a 1 upon failure and a True upon success, which is a little confusing since both evaluate to True in a simple `if postgresql:` statement.  From the docstring it looks like it is supposed to return a False upon failure, but I worked around this with `if postgresql is True` so that a return value of 1 is not considered good.

Note: this notebook uses fuji_test.  I'm ok with merging it as-is if we open another ticket associated with EDR Countdown to switch to fuji after fuji_test is reloaded and approved.

**Comment by weaverba137** [comment]
The manipulation of sys.path is leftover from some testing. The notebook is supposed to use a kernel that has that installed as a tagged version.  I will remove that entirely before merging.

**Comment by weaverba137** [comment]
Hmm, the setup_db return value is an interesting bug.  I will look into that further.

**Comment by weaverba137** [comment]
setup_db will raise an exception if the pgpass details can't be found, which is the more appropriate response. This will be implemented in desihub/specprod-db#4.

**Comment by weaverba137** [comment]
And also note: specprod-db *is* loaded in kernel 23.1, we just need to update desimodules/23.1 with the updated tag after all the database reloading is done.

**Pull request merged**
